### ISSUE TITLE
Improve presentation

### ISSUE THREAD

**Issue by athulin** [Intergalactic-Astronomical-Union/ATEL-EDMC#17]
I'm just looking at the main page in order to figure out if adding ATEL-EDMC would add anything of value.  But I don't see any such information, and there's no obvious pointers. (Perhaps it can be inferred by a description if your database schema, but I have not gone that far right now.)

Suggestion: Add a few words about what ATEL-EDMC collects over and above the main EDMC information.  Of main interest would be information not collected otherwise (Exobio? Astronomical Phenomena? Ring info? Perhaps Asteroid Cluster details? and so on).  

If this information already is available somewhere, link to it.

**Comment by Elite-IGAU** [comment]
https://github.com/Intergalactic-Astronomical-Union/ATEL-EDMC/commit/77c3fe420042b53bdee7c33f880469a12c59c8af
